# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('select_option', models.CharField(max_length=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
