# Generated by Django 5.2.4 on 2025-07-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswers',
            old_name='select_option',
            new_name='selected_option',
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='quesions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestions'),
        ),
    ]
