# Generated by Django 5.2.4 on 2025-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_select_option_quizanswers_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='question_text',
            field=models.TextField(default='Sample question text'),
        ),
    ]
