# Generated by Django 5.2.4 on 2025-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_career_userinfo_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswers',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='catagory',
            field=models.CharField(blank=True, choices=[('A', 'Software Engineer'), ('B', 'UI/UX Designer'), ('C', 'Data Analyst'), ('D', 'Fashion Designer')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification',
            field=models.CharField(default='Not Required', max_length=300),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='skill',
            name='key_skills',
            field=models.TextField(default='Not Required', verbose_name='Key Skills & Competencies'),
        ),
        migrations.AddField(
            model_name='skill',
            name='technology',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='Not Required', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.career'),
        ),
    ]
