# Generated by Django 5.2.4 on 2025-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizanswers_submitted_at_remove_skill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='skill',
            name='certification',
            field=models.CharField(default='Not Required', max_length=500),
        ),
    ]
