# Generated by Django 5.2.4 on 2025-07-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_rename_catagory_skill_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswers',
            old_name='quesions',
            new_name='questions',
        ),
    ]
