# Generated by Django 5.2.4 on 2025-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_quesions_quizanswers_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='certification',
            field=models.TextField(default='ok'),
        ),
    ]
